//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DHL_SCEntities : DbContext
    {
        public DHL_SCEntities()
            : base("name=DHL_SCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<sp_WebAppConsultaBBS_Result> sp_WebAppConsultaBBS(Nullable<int> opc)
        {
            var opcParameter = opc.HasValue ?
                new ObjectParameter("opc", opc) :
                new ObjectParameter("opc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_WebAppConsultaBBS_Result>("sp_WebAppConsultaBBS", opcParameter);
        }
    
        public virtual ObjectResult<sp_WebAppBuscaUsuarioBBS_Result> sp_WebAppBuscaUsuarioBBS(string num_empleado, string cuenta, Nullable<int> opc)
        {
            var num_empleadoParameter = num_empleado != null ?
                new ObjectParameter("num_empleado", num_empleado) :
                new ObjectParameter("num_empleado", typeof(string));
    
            var cuentaParameter = cuenta != null ?
                new ObjectParameter("cuenta", cuenta) :
                new ObjectParameter("cuenta", typeof(string));
    
            var opcParameter = opc.HasValue ?
                new ObjectParameter("opc", opc) :
                new ObjectParameter("opc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_WebAppBuscaUsuarioBBS_Result>("sp_WebAppBuscaUsuarioBBS", num_empleadoParameter, cuentaParameter, opcParameter);
        }
    
        public virtual ObjectResult<sp_WebAppAdmBBS_Result> sp_WebAppAdmBBS(Nullable<System.DateTime> fecha, string num_empleado, string observador, string colaborador, string responsable, string cve_operacion, Nullable<System.TimeSpan> hora, string cve_regla, string sub_regla1, string sub_regla2, string cve_comportamiento, string cve_turno, string observaciones, string cve_empleador, string dia_bbs, Nullable<int> opc)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var num_empleadoParameter = num_empleado != null ?
                new ObjectParameter("num_empleado", num_empleado) :
                new ObjectParameter("num_empleado", typeof(string));
    
            var observadorParameter = observador != null ?
                new ObjectParameter("observador", observador) :
                new ObjectParameter("observador", typeof(string));
    
            var colaboradorParameter = colaborador != null ?
                new ObjectParameter("colaborador", colaborador) :
                new ObjectParameter("colaborador", typeof(string));
    
            var responsableParameter = responsable != null ?
                new ObjectParameter("responsable", responsable) :
                new ObjectParameter("responsable", typeof(string));
    
            var cve_operacionParameter = cve_operacion != null ?
                new ObjectParameter("cve_operacion", cve_operacion) :
                new ObjectParameter("cve_operacion", typeof(string));
    
            var horaParameter = hora.HasValue ?
                new ObjectParameter("hora", hora) :
                new ObjectParameter("hora", typeof(System.TimeSpan));
    
            var cve_reglaParameter = cve_regla != null ?
                new ObjectParameter("cve_regla", cve_regla) :
                new ObjectParameter("cve_regla", typeof(string));
    
            var sub_regla1Parameter = sub_regla1 != null ?
                new ObjectParameter("sub_regla1", sub_regla1) :
                new ObjectParameter("sub_regla1", typeof(string));
    
            var sub_regla2Parameter = sub_regla2 != null ?
                new ObjectParameter("sub_regla2", sub_regla2) :
                new ObjectParameter("sub_regla2", typeof(string));
    
            var cve_comportamientoParameter = cve_comportamiento != null ?
                new ObjectParameter("cve_comportamiento", cve_comportamiento) :
                new ObjectParameter("cve_comportamiento", typeof(string));
    
            var cve_turnoParameter = cve_turno != null ?
                new ObjectParameter("cve_turno", cve_turno) :
                new ObjectParameter("cve_turno", typeof(string));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("observaciones", observaciones) :
                new ObjectParameter("observaciones", typeof(string));
    
            var cve_empleadorParameter = cve_empleador != null ?
                new ObjectParameter("cve_empleador", cve_empleador) :
                new ObjectParameter("cve_empleador", typeof(string));
    
            var dia_bbsParameter = dia_bbs != null ?
                new ObjectParameter("dia_bbs", dia_bbs) :
                new ObjectParameter("dia_bbs", typeof(string));
    
            var opcParameter = opc.HasValue ?
                new ObjectParameter("opc", opc) :
                new ObjectParameter("opc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_WebAppAdmBBS_Result>("sp_WebAppAdmBBS", fechaParameter, num_empleadoParameter, observadorParameter, colaboradorParameter, responsableParameter, cve_operacionParameter, horaParameter, cve_reglaParameter, sub_regla1Parameter, sub_regla2Parameter, cve_comportamientoParameter, cve_turnoParameter, observacionesParameter, cve_empleadorParameter, dia_bbsParameter, opcParameter);
        }
    
        public virtual ObjectResult<sp_WebAppBBS_cons_datos_Result> sp_WebAppBBS_cons_datos(Nullable<int> opc, string cve_filtro_1, string cve_filtro_2)
        {
            var opcParameter = opc.HasValue ?
                new ObjectParameter("opc", opc) :
                new ObjectParameter("opc", typeof(int));
    
            var cve_filtro_1Parameter = cve_filtro_1 != null ?
                new ObjectParameter("cve_filtro_1", cve_filtro_1) :
                new ObjectParameter("cve_filtro_1", typeof(string));
    
            var cve_filtro_2Parameter = cve_filtro_2 != null ?
                new ObjectParameter("cve_filtro_2", cve_filtro_2) :
                new ObjectParameter("cve_filtro_2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_WebAppBBS_cons_datos_Result>("sp_WebAppBBS_cons_datos", opcParameter, cve_filtro_1Parameter, cve_filtro_2Parameter);
        }
    }
}
